[package]
name = "prefix-crab"
version = "0.1.0"
edition = "2021"
authors = ["Philipp Nowak <prefixcrab@phnowak.eu>"]
description = "Friendly multi-call binary crab that inspects IPv6 prefixes to reveal all their secrets"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1", features = ["derive", "unicode"] }
