---
version: "3.2"
#### local use only, do not put this into production (hard-coded credentials) ####

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "localsetupveryinsecure"
    volumes:
      - rmq-data:/var/lib/rabbitmq/
      #- ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      rmq_net:
        ipv4_address: 10.45.87.51
        # http://10.45.87.51:15672/
  postgres:
    image: postgres:15.3-alpine
    container_name: 'prefix-crab-postgres'
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      rmq_net:
        ipv4_address: 10.45.87.52

volumes:
  rmq-data:
    driver: local
  postgres-data:
    driver: local

networks:
  rmq_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.45.87.0/24
          gateway: 10.45.87.1
