---
server:
  retention: 180d

  ## https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read
  remoteRead: []

  tsdb:
    # https://github.com/prometheus/docs/pull/2382/files?short_path=0ef1a9d#diff-0ef1a9d0fd839aa8966cb52ea9d9cc276cbf008d82aaa9290580bab9ad25af39
    # A 10min time window is enough because it can easily absorb retries and network delays.
    out_of_order_time_window: 10m

  ingress:
    enabled: false
    # would need TLS setup + security
  
  persistentVolume:
    enabled: true
    size: 20Gi
    storageClass: rook-ceph-block
  
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  
  extraArgs:
    # https://prometheus.io/docs/prometheus/latest/feature_flags/#otlp-receiver
    enable-feature: "otlp-write-receiver"


alertmanager:
  enabled: false

# cluster-wide state of resources
kube-state-metrics:
  enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

  # Comma-separated list of Kubernetes annotations keys that will be used in the resource'
  # labels metric. By default the metric contains only name and namespace labels.
  # To include additional annotations provide a list of resource names in their plural form and Kubernetes
  # annotation keys you would like to allow for them (Example: '=namespaces=[kubernetes.io/team,...],pods=[kubernetes.io/team],...)'.
  # A single '*' can be provided per resource instead to allow any annotations, but that has
  # severe performance implications (Example: '=pods=[*]').
  metricAnnotationsAllowList: []
  # Comma-separated list of additional Kubernetes label keys that will be used in the resource's
  # labels metric. By default the metric contains only name and namespace labels.
  # To include additional labels, provide a list of resource names in their plural form and Kubernetes
  # label keys you would like to allow for them (Example: '=namespaces=[k8s-label-1,k8s-label-n,...],pods=[app],...)'.
  # A single '*' can be provided per resource instead to allow any labels, but that has
  # severe performance implications (Example: '=pods=[*]').
  metricLabelsAllowlist: []

  # Available collectors for kube-state-metrics.
  # By default, all available resources are enabled, comment out to disable.
  # https://github.com/kubernetes/kube-state-metrics/tree/main/docs
  collectors:
  #- certificatesigningrequests
  #- configmaps
  - cronjobs
  #- daemonsets
  - deployments
  #- endpoints
  #- horizontalpodautoscalers
  #- ingresses
  - jobs
  #- leases
  #- limitranges
  #- mutatingwebhookconfigurations
  - namespaces
  #- networkpolicies
  - nodes
  #- persistentvolumeclaims
  - persistentvolumes
  #- poddisruptionbudgets
  - pods
  - replicasets
  #- replicationcontrollers
  - resourcequotas
  #- secrets
  #- services
  - statefulsets
  #- storageclasses
  #- validatingwebhookconfigurations
  #- volumeattachments

  # Comma-separated list of metrics to be exposed.
  # This list comprises of exact metric names and/or regex patterns.
  # The allowlist and denylist are mutually exclusive.
  metricDenylist: []

# status of k8s nodes (we don't need that probs)
prometheus-node-exporter:
  enabled: false

# seems not needed for OTLP
# https://github.com/prometheus/prometheus/pull/12571/files#diff-315f251cdd7e93fcec1e7e9505744da1d1828f30d2b61d1f4ce963fa26bf1909R393
prometheus-pushgateway:
  enabled: false
