{
 "title": "prefix-crab",
 "time": { "from": "2024-01-18T01:55:49.304Z", "to": "2024-03-04T01:51:49.969Z" },
 "templating": {
  "list": [
   {
    "name": "scheduleInterval",
    "label": "Interval in which new analyses are scheduled",
    "query": "120s"
   },
   { "name": "prefixBudget", "label": "Prefix budget", "query": "1060,1620" },
   { "name": "smoothingInterval", "label": "Smoothing interval", "query": "2m,10m,1h,6h" }
  ]
 },
 "panels": [
  { "title": "Available", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prefixes available for probing (absolute)",
   "type": "timeseries",
   "description": "The read line is the prefix budget: $prefixBudget",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(class) (avg_over_time(prefix_crab_schedule_prefixes_available[$smoothingInterval]))",
     "legendFormat": "{{class}}"
    },
    { "expression": "$prefixBudget", "type": "math" }
   ]
  },
  {
   "title": "Prefixes available for probing (relative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum by(class) (avg_over_time(prefix_crab_schedule_prefixes_available[$smoothingInterval]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  { "title": "Allocation per type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Echo analyses follow ups needed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(follow_up) (prefix_crab_echo_analysis_count_total)",
     "legendFormat": "{{follow_up}}"
    }
   ]
  },
  {
   "title": "Budget allocation per priority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum by(class) (avg_over_time(prefix_crab_schedule_prefixes_allocated[$smoothingInterval]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  { "title": "Allocation per AS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Budget usage per AS (all)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(asn) (sum_over_time(prefix_crab_schedule_asn_allocated[$smoothingInterval]))",
     "legendFormat": "AS{{asn}}"
    }
   ]
  },
  {
   "title": "Budget usage per AS (top-10)",
   "type": "timeseries",
   "description": "\"Other\" are the AS that didn't make it into the top-10 for that bucket",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(prefix_crab_schedule_asn_allocated)-(sum(topk(10, prefix_crab_schedule_asn_allocated)) > 2)",
     "legendFormat": "Other"
    },
    {
     "expr": "sum by(asn) (topk(10, sum_over_time(prefix_crab_schedule_asn_allocated[$smoothingInterval])) > 2)",
     "legendFormat": "AS{{asn}}"
    }
   ]
  },
  { "title": "Split Decisions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Decisions that would split",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(class) (increase(prefix_crab_split_decision_count_v2_total{would_split=\"true\"}[$smoothingInterval]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Decisions that would keep",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum by(class) (increase(prefix_crab_split_decision_count_v2_total{would_split=\"false\"}[$smoothingInterval]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Performed decisions",
   "type": "timeseries",
   "description": "In case of keep, this means that we reached the 255% threshold",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(would_split, class) (increase(prefix_crab_split_decision_count_v2_total{performed=\"true\", would_split!=\"\"}[$smoothingInterval]))",
     "legendFormat": "{{would_split}} - {{class}}"
    }
   ]
  },
  {
   "title": "Not performed decisions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by(would_split, class) (increase(prefix_crab_split_decision_count_v2_total{performed=\"false\", would_split!=\"\"}[$smoothingInterval]))",
     "legendFormat": "{{would_split}} - {{class}}"
    }
   ]
  }
 ]
}