# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/store/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
filter = { except_tables = ["poc_prefix_tree"] }

[migrations_directory]
dir = "migrations"
